version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tarea_db

  app:
    build: .
    container_name: tarea-final-app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/tarea_db
    depends_on:
      - mongo